[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.remappings]
"@prb/math/"="lib/prb-math/src"
"@openzeppelin"="lib/openzeppelin"
via_ir = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
